//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.13 at 01:19:48 PM CET 
//


package hr.algebra.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="People">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Person" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="IDPerson" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Surname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PictureUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "people"
})
@XmlRootElement(name = "ListOfPeople", namespace = "http://schemas.datacontract.org/2004/07/RestService.Models")
public class ListOfPeople {

    @XmlElement(name = "People", namespace = "http://schemas.datacontract.org/2004/07/RestService.Models", required = true)
    protected ListOfPeople.People people;

    /**
     * Gets the value of the people property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfPeople.People }
     *     
     */
    public ListOfPeople.People getPeople() {
        return people;
    }

    /**
     * Sets the value of the people property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfPeople.People }
     *     
     */
    public void setPeople(ListOfPeople.People value) {
        this.people = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Person" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="IDPerson" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Surname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PictureUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "person"
    })
    public static class People {

        @XmlElement(name = "Person", namespace = "http://schemas.datacontract.org/2004/07/RestService.Models", required = true)
        protected List<ListOfPeople.People.Person> person;

        /**
         * Gets the value of the person property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the person property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPerson().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ListOfPeople.People.Person }
         * 
         * 
         */
        public List<ListOfPeople.People.Person> getPerson() {
            if (person == null) {
                person = new ArrayList<ListOfPeople.People.Person>();
            }
            return this.person;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="IDPerson" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Surname" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PictureUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "idPerson",
            "name",
            "surname",
            "gender",
            "pictureUrl"
        })
        public static class Person {

            @XmlElement(name = "IDPerson", namespace = "http://schemas.datacontract.org/2004/07/RestService.Models")
            @XmlSchemaType(name = "unsignedByte")
            protected short idPerson;
            @XmlElement(name = "Name", namespace = "http://schemas.datacontract.org/2004/07/RestService.Models", required = true)
            protected String name;
            @XmlElement(name = "Surname", namespace = "http://schemas.datacontract.org/2004/07/RestService.Models", required = true)
            protected String surname;
            @XmlElement(name = "Gender", namespace = "http://schemas.datacontract.org/2004/07/RestService.Models", required = true)
            protected String gender;
            @XmlElement(name = "PictureUrl", namespace = "http://schemas.datacontract.org/2004/07/RestService.Models", required = true)
            protected String pictureUrl;

            /**
             * Gets the value of the idPerson property.
             * 
             */
            public short getIDPerson() {
                return idPerson;
            }

            /**
             * Sets the value of the idPerson property.
             * 
             */
            public void setIDPerson(short value) {
                this.idPerson = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the surname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSurname() {
                return surname;
            }

            /**
             * Sets the value of the surname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSurname(String value) {
                this.surname = value;
            }

            /**
             * Gets the value of the gender property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGender() {
                return gender;
            }

            /**
             * Sets the value of the gender property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGender(String value) {
                this.gender = value;
            }

            /**
             * Gets the value of the pictureUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPictureUrl() {
                return pictureUrl;
            }

            /**
             * Sets the value of the pictureUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPictureUrl(String value) {
                this.pictureUrl = value;
            }

        }

    }

}
